spring:
  application:
    name: data-service #服务的名字
#  rabbitmq:  #消息队列配置 包含地址、端口、账号、密码
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: Huagao705

#  mongodb:
#    uri: mongodb://name:pass@localhost:27017/database?maxPoolSize=256

  datasource: #sqlserver配置 其中可以改的是 ip、数据库名、username、password
    url: jdbc:sqlserver://127.0.0.1:1433;database=SewagePlatform
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.middleware.data.domain
